spring:
  profiles:
    #包含的配置项
    include:
    - single-datasource
    #      - quartz
    #启用配置项级别
    active: prod
  #色彩日志输出
  output:
    ansi:
      enabled: always
  redis:
    port: 6379
    host: 10.100.1.145
#    password: 123456
  application:
    name: service-oauth
eureka:
  client:
    service-url:
      defaultZone: http://shiyakun:123456@peer1:8760/eureka/,http://shiyakun:123456@peer2:8761/eureka/
  instance:
      #每间隔10s，向服务端发送一次心跳，证明自己依然”存活“
    lease-renewal-interval-in-seconds: 20
      #告诉服务端，如果我20s之内没有给你发心跳，就代表我“死”了，将我踢出掉。
    lease-expiration-duration-in-seconds: 60
mybatis:
  mapper-locations: classpath*:**/mappers/*.xml
  type-aliases-package: com.example.demo.domain.entity
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
    use-column-label: true
    cache-enabled: true
    call-setters-on-nulls: true
logging:
  level:
    root: info
    org:
      springframework: info
server:
  port: 8801